global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'v8-integration'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'v8-performance'
    static_configs:
      - targets: ['localhost:8081']
    scrape_interval: 10s
    metrics_path: /performance
    
  - job_name: 'v8-health'
    static_configs:
      - targets: ['localhost:8082']
    scrape_interval: 30s
    metrics_path: /health

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093