name: CI/CD Pipeline

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        build-type: [Release, Debug]
        compiler: [gcc, clang, msvc]
        exclude:
          # Exclude invalid combinations
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: msvc
          - os: ubuntu-20.04
            compiler: msvc
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc-11
            cxx: g++-11
          - os: ubuntu-latest
            compiler: clang
            cc: clang-12
            cxx: clang++-12
          - os: ubuntu-20.04
            compiler: gcc
            cc: gcc-9
            cxx: g++-9
          - os: ubuntu-20.04
            compiler: clang
            cc: clang-10
            cxx: clang++-10
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libv8-dev \
          libgtest-dev \
          cmake \
          ninja-build \
          valgrind \
          clang-tidy \
          cppcheck \
          doxygen \
          graphviz \
          lcov \
          ${{ matrix.cc }} \
          ${{ matrix.cxx }}

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        # Install vcpkg dependencies
        vcpkg install gtest:x64-windows
        vcpkg install boost-program-options:x64-windows
        # Note: V8 will need to be built from source on Windows
        choco install cmake ninja doxygen.install graphviz

    - name: Setup build environment (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

    - name: Setup build environment (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV
        echo "VCPKG_TARGET_TRIPLET=x64-windows" >> $env:GITHUB_ENV

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DUSE_SYSTEM_V8=ON \
          -DENABLE_TESTING=ON \
          -DENABLE_COVERAGE=ON \
          -DENABLE_SANITIZERS=ON \
          -G Ninja

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -B build `
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} `
          -DUSE_SYSTEM_V8=OFF `
          -DENABLE_TESTING=ON `
          -DENABLE_COVERAGE=OFF `
          -DENABLE_SANITIZERS=OFF `
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -G "Visual Studio 17 2022" `
          -A x64

    - name: Build
      run: cmake --build build --parallel

    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: |
        cd build
        ctest --output-on-failure --parallel

    - name: Run tests (Windows)
      if: runner.os == 'Windows'
      run: |
        cd build
        ctest --output-on-failure --parallel -C ${{ matrix.build-type }}

    - name: Run memory tests with Valgrind
      if: matrix.build-type == 'Debug' && runner.os == 'Linux'
      run: |
        cd build
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./test_suite
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./advanced_test_suite

    - name: Run static analysis (Linux)
      if: runner.os == 'Linux'
      run: |
        cppcheck --enable=all --std=c++17 --project=build/compile_commands.json --error-exitcode=1 || true
        cd build
        make clang-tidy || true

    - name: Run static analysis (Windows)
      if: runner.os == 'Windows'
      run: |
        # Static analysis for Windows can be added here if needed
        echo "Static analysis on Windows - placeholder"

    - name: Generate coverage report
      if: matrix.build-type == 'Debug' && matrix.compiler == 'gcc'
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage to Codecov
      if: matrix.build-type == 'Debug' && matrix.compiler == 'gcc'
      uses: codecov/codecov-action@v3
      with:
        file: build/coverage.info
        flags: unittests
        name: codecov-umbrella

    - name: Generate documentation
      if: matrix.build-type == 'Release' && matrix.compiler == 'gcc'
      run: |
        cd build
        make docs

    - name: Deploy documentation
      if: matrix.build-type == 'Release' && matrix.compiler == 'gcc' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/html

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run security scan
      uses: securecodewarrior/github-action-add-sarif@v1
      with:
        sarif-file: 'security-scan.sarif'

    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: cpp

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t v8-cpp-integration:latest .

    - name: Test Docker image
      run: |
        docker run --rm v8-cpp-integration:latest ./run_tests.sh

    - name: Push to registry
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push v8-cpp-integration:latest

  performance-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libv8-dev libgtest-dev cmake ninja-build

    - name: Build performance tests
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_V8=ON -G Ninja
        cmake --build build --parallel

    - name: Run performance benchmarks
      run: |
        cd build
        ./performance_tests --benchmark_format=json > benchmark_results.json

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: build/benchmark_results.json

  release:
    needs: [build-and-test, security-scan, docker-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false